apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: temporal-server-qa-store
  namespace: default
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: repositories-2b29
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-server-qa-external-secret
  namespace: default
spec:
  secretStoreRef:
    kind: SecretStore
    name: temporal-server-qa-store
  target:
    name: temporal-server-qa
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: temporal-server-qa
  refreshInterval: 10s