apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: temporal-server
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: temporal-server
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
