apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: temporal-server
  namespace: default
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: temporal-server
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal-server
          image: docker.io/temporalio/server:1.29.1
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          envFrom:
            - secretRef:
                name: temporal-server-qa
          ports:
            - name: grpc
              containerPort: 7233
              protocol: TCP
            - name: http
              containerPort: 7234
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: "0.8"
              memory: 1200Mi
            requests:
              cpu: "0.5"
              memory: 1000Mi
          volumeMounts:
            - name: cache-volume
              mountPath: /usr/src/app/cache
  volumeClaimTemplates:
    - metadata:
        name: cache-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
