apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: temporal-server-prod-store
  namespace: agent-simplit
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: repositories-2b29
  retrySettings:
    maxRetries: 5
    retryInterval: 10s
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-server-prod-external-secret
  namespace: agent-simplit
spec:
  secretStoreRef:
    kind: SecretStore
    name: temporal-server-prod-store
  target:
    name: temporal-server-prod
  dataFrom:
  - extract:
      conversionStrategy: Default
      key: temporal-server-prod
  refreshInterval: 10s